name: Build AppImage
on:
  push:
  pull_request:
jobs:
  build-appimage:
    strategy:
      matrix:
        arch: [x86_64-linux]
        app: [photo, designer, publisher]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.garnix.io https://cache.nixos.org/
      - name: build-${{ matrix.arch }}-${{ matrix.app }}
        run: nix build -v -L .#packages.${{ matrix.arch }}.${{ matrix.app }}
      - name: bundle-${{ matrix.arch }}-${{ matrix.app }}
        run: nix bundle -v -L --bundler github:ralismark/nix-appimage .#packages.${{ matrix.arch }}.${{ matrix.app }}
      - name: Upload appimage
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.app }}-${{ github.sha }}
          path: affinity-${{ matrix.app }}-2.AppImage
  publish-appimage:
    needs: [build-appimage]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v5
        name: Download
        with:
          path: artifact
          pattern: \{photo,publisher,designer}-${{ github.sha }}
